In [ ]:
import pandas as pd

gene = pd.read_csv("/content/GSE160306_human_retina_DR_totalRNA_normalized_cpm.csv")
labels = pd.read_csv("/content/GSE160306_series_matrix1.csv")

print(gene.columns)
print(labels.columns)

Index(['ensemblID', 'sample_01', 'sample_10', 'sample_11', 'sample_12',
       'sample_13', 'sample_14', 'sample_15', 'sample_16', 'sample_17',
       'sample_18', 'sample_19', 'sample_02', 'sample_20', 'sample_21',
       'sample_22', 'sample_23', 'sample_24', 'sample_25', 'sample_26',
       'sample_27', 'sample_28', 'sample_29', 'sample_03', 'sample_30',
       'sample_31', 'sample_32', 'sample_33', 'sample_34', 'sample_35',
       'sample_36', 'sample_37', 'sample_38', 'sample_39', 'sample_04',
       'sample_40', 'sample_41', 'sample_42', 'sample_43', 'sample_44',
       'sample_46', 'sample_47', 'sample_48', 'sample_49', 'sample_05',
       'sample_50', 'sample_51', 'sample_52', 'sample_53', 'sample_54',
       'sample_55', 'sample_56', 'sample_57', 'sample_58', 'sample_59',
       'sample_06', 'sample_60', 'sample_61', 'sample_62', 'sample_63',
       'sample_64', 'sample_66', 'sample_67', 'sample_68', 'sample_69',
       'sample_07', 'sample_70', 'sample_71', 'sample_72', 'sample_73',
       'sample_74', 'sample_76', 'sample_77', 'sample_78', 'sample_08',
       'sample_80', 'sample_09'],
      dtype='object')
Index(['!Sample_title', 'sample_01', 'sample_10', 'sample_11', 'sample_12',
       'sample_13', 'sample_14', 'sample_15', 'sample_16', 'sample_17',
       'sample_18', 'sample_19', 'sample_02', 'sample_20', 'sample_21',
       'sample_22', 'sample_23', 'sample_24', 'sample_25', 'sample_26',
       'sample_27', 'sample_28', 'sample_29', 'sample_03', 'sample_30',
       'sample_31', 'sample_32', 'sample_33', 'sample_34', 'sample_35',
       'sample_36', 'sample_37', 'sample_38', 'sample_39', 'sample_04',
       'sample_40', 'sample_41', 'sample_42', 'sample_43', 'sample_44',
       'sample_46', 'sample_47', 'sample_48', 'sample_49', 'sample_05',
       'sample_50', 'sample_51', 'sample_52', 'sample_53', 'sample_54',
       'sample_55', 'sample_56', 'sample_57', 'sample_58', 'sample_59',
       'sample_06', 'sample_60', 'sample_61', 'sample_62', 'sample_63',
       'sample_64', 'sample_65', 'sample_66', 'sample_67', 'sample_68',
       'sample_69', 'sample_07', 'sample_70', 'sample_71', 'sample_72',
       'sample_73', 'sample_74', 'sample_75', 'sample_76', 'sample_77',
       'sample_78', 'sample_79', 'sample_08', 'sample_80', 'sample_09'],
      dtype='object')

In [ ]:
gene_samples = gene.columns[1:]   # ignore ensemblID column
label_samples = labels.columns

common_samples = list(set(gene_samples) & set(label_samples))

print(len(common_samples))

76

In [ ]:
gene_samples = gene.columns[1:]          # skip ensemblID
label_samples = labels.columns[1:]
common_samples = [s for s in gene_samples if s in label_samples]

gene_filtered = gene[["ensemblID"] + common_samples]
labels_filtered = labels[[labels.columns[0]] + common_samples]

In [ ]:
meta = labels_filtered.set_index(labels_filtered.columns[0]).T
meta.index.name = "sample_id"
meta.reset_index(inplace=True)

In [ ]:
if "!Sample_characteristics_ch1" in meta.columns:
    meta["label"] = meta["!Sample_characteristics_ch1"].apply(
        lambda x: "Control" if "Control" in str(x) else "DR"
    )

In [ ]:
rename_dict = {
    "!Sample_geo_accession": "GSM_id",
    "!Sample_title": "sample_title"
}
meta.rename(columns=rename_dict, inplace=True)

In [ ]:
gene_t = gene_filtered.set_index("ensemblID").T
gene_t.index.name = "sample_id"
gene_t.reset_index(inplace=True)

In [ ]:
GSE160306 = pd.merge(meta, gene_t, on="sample_id", how="inner")

In [ ]:
GSE160306.to_excel("/content/GSE160306_data.xlsx", index=False)
GSE160306.to_csv("/content/GSE160306_data.csv", index=False)

print(GSE160306.head())
print( GSE160306.shape)

   sample_id !Sample_characteristics_ch1      ID_REF    label  \
0  sample_01                     Control  GSM4871112  Control
1  sample_10                     Control  GSM4871113  Control
2  sample_11                     Control  GSM4871114  Control
3  sample_12                     Control  GSM4871115  Control
4  sample_13                     Control  GSM4871116  Control

   ENSG00000000003  ENSG00000000419  ENSG00000000457  ENSG00000000460  \
0        13.296876        14.473577        14.855904        14.081856
1        13.055670        14.364616        15.377383        14.339404
2        13.445849        14.494166        15.263427        14.229668
3        13.812388        14.662366        15.784155        14.532957
4        13.475160        14.921105        15.043298        13.933490

   ENSG00000000971  ENSG00000001036  ...  ENSG00000283183  ENSG00000283199  \
0        12.618348        14.055223  ...        14.855904        12.891353
1        13.484874        13.419066  ...        14.896788        13.244137
2        12.831553        13.214436  ...        14.051851        12.025755
3        14.697344        13.493135  ...        13.714660        12.818959
4        13.803471        13.261301  ...        13.216314        13.531782

   ENSG00000283236  ENSG00000283312  ENSG00000283341  ENSG00000283417  \
0        13.787631        11.274930        13.361997        13.073251
1        13.836431        11.517020        13.814039        13.134604
2        13.744492        11.260701        13.461980        12.745067
3        13.764392        11.749387        13.946742        12.452357
4        13.769266        11.151620        13.598736        13.479718

   ENSG00000283486  ENSG00000283503  ENSG00000283536  ENSG00000283674
0        12.701134        13.106211        13.251315        14.157047
1        12.430274        12.710828        13.406005        13.706553
2        13.328754        13.098244        14.074766        13.721254
3        12.895812        12.397418        14.353153        12.587136
4        12.007213        11.550052        12.910201        13.216314

[5 rows x 15070 columns]
(76, 15070)

In [ ]:
pd.read_csv("/content/GSE160306.csv")

,Sample,ENSG00000000003,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,ENSG00000001460,...,ENSG00000283183,ENSG00000283199,ENSG00000283236,ENSG00000283312,ENSG00000283341,ENSG00000283417,ENSG00000283486,ENSG00000283503,ENSG00000283536,ENSG00000283674
0,Control,13.296876,14.473577,14.855904,14.081856,12.618348,14.055223,16.924684,15.973886,16.100875,...,14.855904,12.891353,13.787631,11.274930,13.361997,13.073251,12.701134,13.106211,13.251315,14.157047
1,Control,13.055670,14.364616,15.377383,14.339404,13.484874,13.419066,16.518363,16.307698,15.846195,...,14.896788,13.244137,13.836431,11.517020,13.814039,13.134604,12.430274,12.710828,13.406005,13.706553
2,Control,13.445849,14.494166,15.263427,14.229668,12.831553,13.214436,16.729033,16.160798,15.891618,...,14.051851,12.025755,13.744492,11.260701,13.461980,12.745067,13.328754,13.098244,14.074766,13.721254
3,Control,13.812388,14.662366,15.784155,14.532957,14.697344,13.493135,16.100795,16.841618,16.208667,...,13.714660,12.818959,13.764392,11.749387,13.946742,12.452357,12.895812,12.397418,14.353153,12.587136
4,Control,13.475160,14.921105,15.043298,13.933490,13.803471,13.261301,16.958059,16.081452,15.673948,...,13.216314,13.531782,13.769266,11.151620,13.598736,13.479718,12.007213,11.550052,12.910201,13.216314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,DR,13.567362,14.492131,15.809168,14.327635,13.200165,13.261842,16.232468,16.549285,15.805297,...,14.004710,13.200669,13.720348,11.519279,13.567959,13.478697,12.995041,12.242772,14.092609,13.547808
72,DR,14.806184,14.188908,15.464621,14.185955,15.520754,14.715565,16.928254,16.382395,15.180884,...,14.153708,13.101334,13.499985,11.376729,13.242530,14.805483,11.523102,13.056936,12.711970,14.748321
73,Control,13.455301,14.526534,15.279205,14.307587,13.747046,14.012620,16.670265,16.213922,16.260938,...,15.210361,13.374176,13.597462,11.594921,13.772216,13.126396,12.371974,13.228578,13.589184,13.675295
74,DR,14.156278,14.629324,15.864178,14.480851,12.588662,13.299744,16.512324,16.706663,15.973711,...,13.879815,13.076897,14.125515,11.881480,14.067897,13.387794,12.584424,12.912039,13.333385,13.214132
75,Control,12.743279,14.517209,15.621549,14.171032,14.570144,12.967945,16.443175,16.664634,16.207501,...,14.959821,13.226204,13.642197,11.575630,13.932754,12.947081,12.803982,12.792244,14.083537,13.543216

In [ ]:
import pandas as pd
import mygene

# load file
df = pd.read_csv("/content/GSE160306.csv")

# first column is Sample, all other columns are ENSG IDs
ensembl_ids = df.columns[1:].tolist()

# remove version numbers if present
ensembl_ids = [x.split(".")[0] for x in ensembl_ids]

# query mygene
mg = mygene.MyGeneInfo()
results = mg.querymany(
    ensembl_ids,
    scopes="ensembl.gene",
    fields="symbol",
    species="human"
)

# build mapping
ensembl_to_symbol = {}
for r in results:
    ensg = r.get("query")
    symbol = r.get("symbol", ensg)  # keep ENSG if no symbol found
    ensembl_to_symbol[ensg] = symbol

# rename gene columns
new_columns = ["Sample"] + [ensembl_to_symbol.get(col.split(".")[0], col) for col in df.columns[1:]]
df.columns = new_columns

# save
df.to_csv("/content/GSE160306_with_gene_symbols.csv", index=False)

print(df.head())

WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
INFO:biothings.client:querying 1-1000 ...
INFO:biothings.client:querying 1001-2000 ...
INFO:biothings.client:querying 2001-3000 ...
INFO:biothings.client:querying 3001-4000 ...
INFO:biothings.client:querying 4001-5000 ...
INFO:biothings.client:querying 5001-6000 ...
INFO:biothings.client:querying 6001-7000 ...
INFO:biothings.client:querying 7001-8000 ...
INFO:biothings.client:querying 8001-9000 ...
INFO:biothings.client:querying 9001-10000 ...
INFO:biothings.client:querying 10001-11000 ...
INFO:biothings.client:querying 11001-12000 ...
INFO:biothings.client:querying 12001-13000 ...
INFO:biothings.client:querying 13001-14000 ...
INFO:biothings.client:querying 14001-15000 ...
INFO:biothings.client:querying 15001-15066 ...
INFO:biothings.client:Finished.
WARNING:biothings.client:3 input query terms found dup hits:	[('ENSG00000175711', 2), ('ENSG00000227110', 2), ('ENSG00000228044', 2)]
WARNING:biothings.client:160 input query terms found no hit:	['ENSG00000112096', 'ENSG00000116883', 'ENSG00000116957', 'ENSG00000130489', 'ENSG00000130723', 'ENS
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

    Sample     TSPAN6       DPM1      SCYL3      FIRRM        CFH      FUCA2  \
0  Control  13.296876  14.473577  14.855904  14.081856  12.618348  14.055223
1  Control  13.055670  14.364616  15.377383  14.339404  13.484874  13.419066
2  Control  13.445849  14.494166  15.263427  14.229668  12.831553  13.214436
3  Control  13.812388  14.662366  15.784155  14.532957  14.697344  13.493135
4  Control  13.475160  14.921105  15.043298  13.933490  13.803471  13.261301

        GCLC       NFYA      STPG1  ...  LOC105374338   C13orf46  \
0  16.924684  15.973886  16.100875  ...     14.855904  12.891353
1  16.518363  16.307698  15.846195  ...     14.896788  13.244137
2  16.729033  16.160798  15.891618  ...     14.051851  12.025755
3  16.100795  16.841618  16.208667  ...     13.714660  12.818959
4  16.958059  16.081452  15.673948  ...     13.216314  13.531782

   ENSG00000283236  ENSG00000283312  ENSG00000283341  ENSG00000283417  \
0        13.787631        11.274930        13.361997        13.073251
1        13.836431        11.517020        13.814039        13.134604
2        13.744492        11.260701        13.461980        12.745067
3        13.764392        11.749387        13.946742        12.452357
4        13.769266        11.151620        13.598736        13.479718

   ENSG00000283486  LINC01902  LOC122455340  LOC729732
0        12.701134  13.106211     13.251315  14.157047
1        12.430274  12.710828     13.406005  13.706553
2        13.328754  13.098244     14.074766  13.721254
3        12.895812  12.397418     14.353153  12.587136
4        12.007213  11.550052     12.910201  13.216314

[5 rows x 15067 columns]

In [ ]:
pd.read_csv("/content/GSE160306_with_gene_symbols.csv")

,Sample,TSPAN6,DPM1,SCYL3,FIRRM,CFH,FUCA2,GCLC,NFYA,STPG1,...,LOC105374338,C13orf46,ENSG00000283236,ENSG00000283312,ENSG00000283341,ENSG00000283417,ENSG00000283486,LINC01902,LOC122455340,LOC729732
0,Control,13.296876,14.473577,14.855904,14.081856,12.618348,14.055223,16.924684,15.973886,16.100875,...,14.855904,12.891353,13.787631,11.274930,13.361997,13.073251,12.701134,13.106211,13.251315,14.157047
1,Control,13.055670,14.364616,15.377383,14.339404,13.484874,13.419066,16.518363,16.307698,15.846195,...,14.896788,13.244137,13.836431,11.517020,13.814039,13.134604,12.430274,12.710828,13.406005,13.706553
2,Control,13.445849,14.494166,15.263427,14.229668,12.831553,13.214436,16.729033,16.160798,15.891618,...,14.051851,12.025755,13.744492,11.260701,13.461980,12.745067,13.328754,13.098244,14.074766,13.721254
3,Control,13.812388,14.662366,15.784155,14.532957,14.697344,13.493135,16.100795,16.841618,16.208667,...,13.714660,12.818959,13.764392,11.749387,13.946742,12.452357,12.895812,12.397418,14.353153,12.587136
4,Control,13.475160,14.921105,15.043298,13.933490,13.803471,13.261301,16.958059,16.081452,15.673948,...,13.216314,13.531782,13.769266,11.151620,13.598736,13.479718,12.007213,11.550052,12.910201,13.216314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,DR,13.567362,14.492131,15.809168,14.327635,13.200165,13.261842,16.232468,16.549285,15.805297,...,14.004710,13.200669,13.720348,11.519279,13.567959,13.478697,12.995041,12.242772,14.092609,13.547808
72,DR,14.806184,14.188908,15.464621,14.185955,15.520754,14.715565,16.928254,16.382395,15.180884,...,14.153708,13.101334,13.499985,11.376729,13.242530,14.805483,11.523102,13.056936,12.711970,14.748321
73,Control,13.455301,14.526534,15.279205,14.307587,13.747046,14.012620,16.670265,16.213922,16.260938,...,15.210361,13.374176,13.597462,11.594921,13.772216,13.126396,12.371974,13.228578,13.589184,13.675295
74,DR,14.156278,14.629324,15.864178,14.480851,12.588662,13.299744,16.512324,16.706663,15.973711,...,13.879815,13.076897,14.125515,11.881480,14.067897,13.387794,12.584424,12.912039,13.333385,13.214132
75,Control,12.743279,14.517209,15.621549,14.171032,14.570144,12.967945,16.443175,16.664634,16.207501,...,14.959821,13.226204,13.642197,11.575630,13.932754,12.947081,12.803982,12.792244,14.083537,13.543216

In [ ]:
df = pd.read_csv("/content/GSE160306_with_gene_symbols.csv")
print(df.columns[:10])

Index(['Sample', 'TSPAN6', 'DPM1', 'SCYL3', 'FIRRM', 'CFH', 'FUCA2', 'GCLC',
       'NFYA', 'STPG1'],
      dtype='object')

In [ ]:
import pandas as pd
import mygene

df = pd.read_csv("/content/GSE160306_with_gene_symbols.csv")

ensg_cols = [c for c in df.columns if c.startswith("ENSG")]
print(len(ensg_cols))

773

In [ ]:
mg = mygene.MyGeneInfo()

results = mg.querymany(
    ensg_cols,
    scopes="ensembl.gene",
    fields="symbol",
    species="human"
)

mapping = {}

for r in results:
    query = r.get("query")
    symbol = r.get("symbol")

    if symbol:
        mapping[query] = symbol
    else:
        mapping[query] = query  # keep ENSG if no mapping

WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
INFO:biothings.client:querying 1-773 ...
INFO:biothings.client:Finished.
WARNING:biothings.client:160 input query terms found no hit:	['ENSG00000112096', 'ENSG00000116883', 'ENSG00000116957', 'ENSG00000130489', 'ENSG00000130723', 'ENS
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [ ]:
df.rename(columns=mapping, inplace=True)

df.to_csv("/content/GSE160306_gene_symbols_updated.csv", index=False)

In [ ]:
pd.read_csv("/content/GSE160306_gene_symbols_updated.csv")

,Sample,TSPAN6,DPM1,SCYL3,FIRRM,CFH,FUCA2,GCLC,NFYA,STPG1,...,LOC105374338,C13orf46,ENSG00000283236,ENSG00000283312,ENSG00000283341,ENSG00000283417,ENSG00000283486,LINC01902,LOC122455340,LOC729732
0,Control,13.296876,14.473577,14.855904,14.081856,12.618348,14.055223,16.924684,15.973886,16.100875,...,14.855904,12.891353,13.787631,11.274930,13.361997,13.073251,12.701134,13.106211,13.251315,14.157047
1,Control,13.055670,14.364616,15.377383,14.339404,13.484874,13.419066,16.518363,16.307698,15.846195,...,14.896788,13.244137,13.836431,11.517020,13.814039,13.134604,12.430274,12.710828,13.406005,13.706553
2,Control,13.445849,14.494166,15.263427,14.229668,12.831553,13.214436,16.729033,16.160798,15.891618,...,14.051851,12.025755,13.744492,11.260701,13.461980,12.745067,13.328754,13.098244,14.074766,13.721254
3,Control,13.812388,14.662366,15.784155,14.532957,14.697344,13.493135,16.100795,16.841618,16.208667,...,13.714660,12.818959,13.764392,11.749387,13.946742,12.452357,12.895812,12.397418,14.353153,12.587136
4,Control,13.475160,14.921105,15.043298,13.933490,13.803471,13.261301,16.958059,16.081452,15.673948,...,13.216314,13.531782,13.769266,11.151620,13.598736,13.479718,12.007213,11.550052,12.910201,13.216314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,DR,13.567362,14.492131,15.809168,14.327635,13.200165,13.261842,16.232468,16.549285,15.805297,...,14.004710,13.200669,13.720348,11.519279,13.567959,13.478697,12.995041,12.242772,14.092609,13.547808
72,DR,14.806184,14.188908,15.464621,14.185955,15.520754,14.715565,16.928254,16.382395,15.180884,...,14.153708,13.101334,13.499985,11.376729,13.242530,14.805483,11.523102,13.056936,12.711970,14.748321
73,Control,13.455301,14.526534,15.279205,14.307587,13.747046,14.012620,16.670265,16.213922,16.260938,...,15.210361,13.374176,13.597462,11.594921,13.772216,13.126396,12.371974,13.228578,13.589184,13.675295
74,DR,14.156278,14.629324,15.864178,14.480851,12.588662,13.299744,16.512324,16.706663,15.973711,...,13.879815,13.076897,14.125515,11.881480,14.067897,13.387794,12.584424,12.912039,13.333385,13.214132
75,Control,12.743279,14.517209,15.621549,14.171032,14.570144,12.967945,16.443175,16.664634,16.207501,...,14.959821,13.226204,13.642197,11.575630,13.932754,12.947081,12.803982,12.792244,14.083537,13.543216